# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jake Pulitzer
title: Marketing Analyst
email: pulitzer.jake@gmail.com
# website: www.github.com/jake

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: pulitzer_jake
github_username:  jakepulitzer
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jake_pulitzer
linkedin_username: jacob-pulitzer
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: jake-pulitzer-portfolio
  icon: fas fa-globe
  url: https://jakepulitzer.wordpress.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/IMG_0082.jpeg
about_content: | # this will include new lines to allow paragraphs (Note: do not adjust formatting below or else you will break the build! Must be indented and directly below this line.)
    Hi, My name is Jake Pulitzer. I am a motivated and hard working Marketing Analyst hoping to make a positive impact in the clean tech and sustainable energy sectors. Specializing in customer-facing products and programs powered by AMI technology (smart meters), I work on a start-up like team that uses Agile and Lean business management methodologies to drive continuous improvement. I excel at building relationships with internal and external stakeholders, leading the development of complex marketing campaigns in Salesforce, and monitoring customer behavior and engagement data. My problem-solving mindset drives me to analyze program performance, identify key areas to improve customer experience, and make process improvement recommendations to management. With a Master's in Business Analytics and a Bachelor's in Strategic Communications from the University of Colorado Boulder, I stay up-to-date on the latest tech, marketing, and CX trends in the utility industry and clean tech sector. Outside of work, I am an aspiring entrepreneur, outdoor enthusiast, and am always ready to take on challenges and dive into innovative solutions.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Project 1
  #       link: github.com/jakepulitzer
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Xcel Energy
        link: xcelenergy.com
        link_text: XcelEnergy.com
        sub_title: Marketing Analyst
        caption: October 2021 - present
        # quote: >
        #   [INSERT QUOTE HERE]
        description: | # this will include new lines to allow paragraphs
            * Build reports and dashboards to monitor and analyze product and marketing performance metrics to identify issues and optimize effectiveness of future campaigns using lean methodologies; deliver recommendations to product managers and leadership for further segmentation, resulting in 200% increase in campaign effectiveness
            * Work with product managers to identify and define KPI’s for tracking product portfolio performance; pulled reports from variety of sources including Salesforce.com and other legacy systems to report to leadership and external stakeholders
            * Developed process for building, testing, launching and monitoring email campaigns to achieve operational excellence; documented tasks and steps to ensure repeatable process with seamless knowledge transfer
            * Designed and implimented strategic marketing campaign which gained Xcel Energy recognition from SECC as a leader in Consumer Education for a robust, multi-channel campaign that helped consumers learn the specifics of a new time-of-use rate and empowered them to manage their energy use
      - layout: left
        title: Pulitzer Family Law
        link: https://pulitzerfamilylaw.com
        link_text: PulitzerFamilyLaw.com
        sub_title: Intern / Marketing Consultant
        caption: June 2019 - August 2021
        # quote: >
        #   [INSERT QUOTE HERE]
        description: |
            * Developed marketing strategies for customer acquisition; implimented tactics including office relocation and segment pivot resulting in increase in revenue and reduction in total billed hours.
            * Built various dashboard utilizing Google Analytics to optimize campaign effectiveness; tracked leads from multiple law directories and reallocated a $20,000 marketing budget to maximize ROI based on historical ad performance
            * Oversaw web development team to ensure project build was completed in designated timeframe and within budget while maintaining brand standards and company values
      - layout: left
        title: 8z Real Estate
        link: https://8z.com/
        link_text: 8z.com
        sub_title: Marketing Intern
        caption: August 2019 - December 2019
        # quote: >
        #   [INSERT QUOTE HERE]
        description: |
            * Created webpages and configured newsletter email automation for 80+ raeltors utilizing Adobe Dreamweaver, HTML, CSS, WordPress, and Mailchimp
            * Assisted Marketing Director with inventory management to establish homogeneous display of brand image across 8 offices in Colorado; showcased strong written and verbal communication skills to eliminate delay in marketing materials
            * Devised targeted social media campaigns and defined clear customer segmentation strategy to increase total impressions; collaborated with CMO and client care team to manage omni-channel marketing campaigns
      - layout: left
        title: Untapped Learning
        link: https://untappedlearning.com/
        link_text: untappedlearning.com
        sub_title: Student Mentor
        caption: August 2018 - June 2019
        # quote: >
        #   [INSERT QUOTE HERE]
        description: |
            * Managed group of 70+ high school student athletes with executive functioning disorders
            * Tracked academic progress of 5 students, identifying areas of weakness in Math, Science, and Writing; planned study schedules and conducted individual remedial lessons leading to a 30% increase in academic performance
    # USE SECTION BELOW AS TEMPLATE FOR SECTION INFO
      # - layout: left
      #   title: COMPANY NAME
      #   link: LINK TO WEBSITE
      #   link_text: TEXT TO DISPLAY
      #   sub_title: POSITION TITLE
      #   caption: DATES WORKED
      #   # quote: >
      #   #   [INSERT QUOTE HERE]
      #   description: |
      #       * Bullet 1
      #       * Bullet 2
      #       * Bullet 3

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: top-left
        title: Master of Science in Business Analytics
        sub_title: University of Colorado Boulder, Leeds School of Business
        caption: GPA 3.7
        caption: July 2020 - May 2021
        description: |
          During my Master's program at Leeds School of Business I gained extensive knowledge in data science, market analyis, and business management which I continue to use in my everyday work. I also learned and developed technical coding skills in `python`, `SQL`, `RStudio`, `JSON`, `CSS`, and `HTML` through various courses and group projects.

          Some of the projects I worked on include:
          - Built and normalized MySQL database for mock beer company; ran advanced queries, developed user defined functions, and integrated database with Tableau to create informative dashboards and visualizations
          - Developed ML classification model for Arrow Electronics to predict the likelihood of a customer order receiving a discount.
          - Scraped twitter data to conduct network analysis of 3 whisky brands to analyse current brand positioning and identify areas of opportunity. Preprocessed text with tokenization, sentiment analysis, and stopword removal to ensure I derived actionable insights for business recommendations.
          - Created customer retention and acquisition models for woman's apparel brand by computing individual level customer lifetime value measures and utilizing results to assess profitability of customer retention efforts. 
      ---
      - layout: top-left
        title: Bachelor of Science in Strategic Communications, Minor in Business Entrepreneurship
        sub_title: University of Colorado Boulder
        caption: GPA 3.5
        caption: August 2016 - May 2020
        description: |
          While pursuing my Bachelor's degree at the University of Colorado Boulder I developed numerous skills including project management, team work, market research, start-up business analysis, and creative strategic thinking. I worked on numerous class projects focused on re-branding established companys, conducting quantitative and qualitative market research, and utilizing standardized processes for start-up business development.

          In addition to my school projects, I was a member of Chi Psi Fraternity where I held Banquet Chairman position. As the Banquet Charman I acted as a liason between fratenity members and the kitchen staff to ensure brotherhood satisfaction. This included coordinating large banquet events, reporting meal recommendations to head Chef based on brotherhood feedback, and assisting finance chairman with managing food budget and making cuts where neccessary.

  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Additional Skills:
      - Strong interpersonal skills
      - Excellent written and verbal communication skills
      - Strong Quantitative and Qualitative research
      - Data visualization tools (PowerBI, Tableau, SAP Analytics Cloud, Looker Studio)
      - Python Libraries for data analysis (pandas, NumPy, SciKit-Learn, Matplotlib, seaborn, TensorFlow)
      - Microsoft Office 365 Expert (Excel, Word, PowerPoint, Teams, OneDrive, Sharepoint, PowerAutomate, Lists, Forms)
      - Project management software (Jira, Confluence, GitHub)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
